name: Check PR
on: [pull_request]
concurrency:
  group: check-pr-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    strategy:
      matrix:
        node: ['14', '16', '17']
    env:
      GCP_PROJECT: qatalog-gcp-config-test
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: install deps
        run: npm i
      - name: setup gcp
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: qatalog-gcp-config-test
          service_account_key: ${{ secrets.TEST_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: lint
        run: npm run lint
      - name: test
        run: npm t
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: init
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: analyse
        uses: github/codeql-action/analyze@v1
